# Generated by Django 4.0.5 on 2022-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetShop', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[1, 'consulta'], [2, 'reclamo'], [3, 'sugerencia'], [4, 'felicitaciones']]),
        ),
    ]
